import express from 'express';
import { userRouter } from '../routes/admin/user.route';
import { roleRouter } from '../routes/admin/roles.route';
import { countryRouter } from '../routes/admin/country.route';
import { overViewRouter } from '../routes/admin/overView.route';
import { propertyTypeRouter } from '../routes/admin/propertyType.route';
import { tagsRouter } from '../routes/admin/tags.route';
import { amenityRouter } from '../routes/admin/amenities.route';
import { furnishingTypeRouter } from '../routes/admin/furnishingType.route';
import { bedRoomTypeRouter } from '../routes/admin/bedRoomType.route';
import { addInfoRouter } from '../routes/admin/additionalInfo.route';
import { nationalitiesRouter } from '../routes/admin/nationalities.route';
import { termsAndConditionRouter } from '../routes/admin/terms&Condtion.route';
import { agencyRouter } from '../routes/admin/agency.route';
import { languagesRouter } from '../routes/admin/languages.route';
import { specialitiesRouter } from '../routes/admin/specialities.route';
export const adminRouter = express.Router();

adminRouter.use('/users', userRouter);
adminRouter.use('/role', roleRouter);
adminRouter.use('/country', countryRouter);
adminRouter.use('/overView', overViewRouter);
adminRouter.use('/propertyType', propertyTypeRouter);
adminRouter.use('/tag', tagsRouter);
adminRouter.use('/amenity', amenityRouter);
adminRouter.use('/furnish', furnishingTypeRouter);
adminRouter.use('/bedRoom', bedRoomTypeRouter);
adminRouter.use('/additionalInfo', addInfoRouter);
adminRouter.use('/nationality', nationalitiesRouter);
adminRouter.use('/termsAndCondition', termsAndConditionRouter);
adminRouter.use('/agency', agencyRouter);
adminRouter.use('/languages', languagesRouter);
adminRouter.use('/specialities', specialitiesRouter);
